### PR TITLE
Waitingroom ts

### LINKED ISSUE #19: create room

### LINKED ISSUE #37: Only owner can edit things in waiting room
Only owner of the room should be able to edit room settings.
Check from jwt isOwner and add disable to inputs if not owner

### LINKED ISSUE #43: Create actual game room over ws and update game state stuff to only room members
- [x] Add authorize event before anything happens and check jwt
- [x] Create room in the ws server and keep client info up to date
- [x] Update settings in waiting room to all clients in the room but not to anyone else
- [x] Start game starts the game on every client
- [x] Pass in settings and player list from the waiting area to game area
- [x] Update move card event to only broadcast to players in room
- [x] Update flipcard event to only broadcast to players in room
- [x] Kick player
- [x] Redirect if room is full

### PR DESCRIPTION
**Pull request by lassesuomela**
Users are authenticated when they first create request to ws server. If user is not authenticated ws connection will be closed.
Users info and rooms are tracked on ws server.
Rooms are created in ws server so events dont leak to other users.
Player list updates in waiting room.
Game settings update in real time to every player in the room.
Only owner of the room can make changes to settings.
Start game starts the game on every player in the same room and renders game area
Game area takes in game settings and players as props
Username and user id are shown correctly on the "hand" on game area.
Move-card and flip-card actions only go to players in the same room.
Owner can kick players
Can join to lobby with url if user has token otherwise will be redirected to create token

Known issues:
When user A takes card from deck it takes it from the top in user A window and in B user's window it takes the card from the bottom of the deck or something
PlayerList needs some attention in waiting room some css stuff is needed

### CODE REVIEW

**Comment by lassesuomela** [comment]
After merge add #37 #43 #19 to your pr

**Comment by ryksyy** [comment]
If a room is full and you try to connect to the same room once a game is in progress you will be redirected to the room settings page where you can start a new game with the same id.

This seems to also break every subsequent new connection, atleast I was not able to start a different game under new id and players once one lobby was broken like that

**Review by ryksyy — CHANGES_REQUESTED** [review]
See comment

**Review by ryksyy — APPROVED** [review]

**Review by ryksyy — APPROVED** [review]
lgtm

**Pull request merged**
